# Generated by Django 5.1.1 on 2024-09-20 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='Title',
            new_name='title',
        ),
    ]
